run_name: "Demo"
run_strategy: "epoch"
run_duration: 1
seed: 322
dry_run: False
save_folder: "./"
save_num_checkpoints_to_keep: 1
device_train_batch_size: 32
device_eval_batch_size: 32
max_grad_norm: 1.0
precision: amp_fp16
gradient_accumulation_steps: 1
activation_checkpointing: False
accelerator_type: "cpu"

optimizer:
  name: "adamw"
  learning_rate: 0.0002
  weight_decay: 0.
  betas: [ 0.9, 0.95 ]

scheduler:
  name: "cosine_annealing"
  t_warmup: 100
  t_min: 0.000001

wandb:
  enabled: False

deepspeed:
  enabled: False

fsdp:
  enabled: False

